In [138]:
import pandas as pd
import numpy as np
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import warnings
warnings.filterwarnings("ignore")
nltk.download('punkt_tab')
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\SAIYAN\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

In [139]:
df = pd.read_csv("spam.csv")

In [140]:
df.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [141]:
df.describe()

       Category                 Message
count      5572                    5572
unique        2                    5157
top         ham  Sorry, I'll call later
freq       4825                      30

In [142]:
df.isnull().sum()

Category    0
Message     0
dtype: int64

In [143]:
df.duplicated().sum()

np.int64(415)

In [144]:
df = df.drop_duplicates()

In [145]:
df.describe()

       Category                     Message
count      5157                        5157
unique        2                        5157
top         ham  Rofl. Its true to its name
freq       4516                           1

In [146]:
nltk.download('punkt')
nltk.download('stopwords')
def tokenization(msg):
    msg = msg.lower()
    tokens = word_tokenize(msg)

    stop_words = set(stopwords.words('english'))

    filtered_words = [word for word in tokens if word not in stop_words]

    return " ".join(filtered_words)

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\SAIYAN\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\SAIYAN\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [147]:
df["clean_message"] = df["Message"].apply(tokenization)

In [148]:
df = df.drop("Message",axis=1)

In [149]:
df["Category"].replace("ham", 0, inplace=True)
df["Category"].replace("spam", 1, inplace=True)

In [150]:
tfidf = TfidfVectorizer()
X=tfidf.fit_transform(df["clean_message"])

In [151]:
y = df['Category']

In [152]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [153]:
model = MultinomialNB()
model.fit(X_train, y_train)

MultinomialNB()

In [154]:
y_pred = model.predict(X_test)

In [155]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.96      1.00      0.98       896
           1       1.00      0.76      0.86       136

    accuracy                           0.97      1032
   macro avg       0.98      0.88      0.92      1032
weighted avg       0.97      0.97      0.97      1032